from tkinter import *
def button_click(number):
    current = e.get()
    e.delete(0, END)
    e.insert(0, current + str(number))
def clear():
    e.delete(0, END)
def calculate():
    try:
        result = eval(e.get())
        e.delete(0, END)
        e.insert(0, result)
    except:
        e.delete(0, END)
        e.insert(0, "Error")
root = Tk()
root.title("Calculator")
e = Entry(root, width=40, borderwidth=5)
e.grid(row=0, column=0, columnspan=4, padx=10, pady=10)
button1 = Button(root, text="1", padx=40, pady=20, command=lambda: button_click(1),fg="yellow",bg="black")
button2 = Button(root, text="2", padx=40, pady=20, command=lambda: button_click(2),fg="yellow",bg="black")
button3 = Button(root, text="3", padx=40, pady=20, command=lambda: button_click(3),fg="yellow",bg="black")
button4 = Button(root, text="4", padx=40, pady=20, command=lambda: button_click(4),fg="yellow",bg="black")
button5 = Button(root, text="5", padx=40, pady=20, command=lambda: button_click(5),fg="yellow",bg="black")
button6 = Button(root, text="6", padx=40, pady=20, command=lambda: button_click(6),fg="yellow",bg="black")
button7 = Button(root, text="7", padx=40, pady=20, command=lambda: button_click(7),fg="yellow",bg="black")
button8 = Button(root, text="8", padx=40, pady=20, command=lambda: button_click(8),fg="yellow",bg="black")
button9 = Button(root, text="9", padx=40, pady=20, command=lambda: button_click(9),fg="yellow",bg="black")
button0 = Button(root, text="0", padx=40, pady=20, command=lambda: button_click(0),fg="yellow",bg="black")
buttonadd = Button(root, text="+", padx=40, pady=20, command=lambda: button_click('+'),fg="yellow",bg="black")
buttonsub = Button(root, text="-", padx=40, pady=20, command=lambda: button_click('-'),fg="yellow",bg="black")
buttonmul = Button(root, text="*", padx=40, pady=20, command=lambda: button_click('*'),fg="yellow",bg="black")
buttondiv = Button(root, text="/", padx=40, pady=20, command=lambda: button_click('/'),fg="yellow",bg="black")
buttonequal = Button(root, text="=", padx=40, pady=20, command=calculate,fg="yellow",bg="black")
buttonclear = Button(root, text="C", padx=40, pady=20, command=clear,fg="yellow",bg="black")
button7.grid(row=1, column=0)
button8.grid(row=1, column=1)
button9.grid(row=1, column=2)
buttonadd.grid(row=1, column=3)
button4.grid(row=2, column=0)
button5.grid(row=2, column=1)
button6.grid(row=2, column=2)
buttonsub.grid(row=2, column=3)
button1.grid(row=3, column=0)
button2.grid(row=3, column=1)
button3.grid(row=3, column=2)
buttonmul.grid(row=3, column=3)
buttonequal.grid(row=4, column=0)
button0.grid(row=4, column=1)
buttonclear.grid(row=4, column=2)
buttondiv.grid(row=4, column=3)
root.mainloop()
